---

- name: "Drop database {{ db_name }}"
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    state: absent

- name: set facility var
  set_fact:
    inventory_file_key: "{{ (inventory_file | basename).split('.')[0] }}"

- name : "Drop users from vars file loop"
  include_tasks: drop_database_users_loop.yml
  loop: "{{ pg_users[inventory_file_key][db_name] }}"
  loop_control:
    loop_var: db_user_params
    label: "db_name {{ db_name }} / db_user {{ db_user_params.db_user }}"
